services:
  adameds_laporan:
    container_name: adameds-laporan
    image: adameds_laporan:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    restart: always
    environment:
      DOTENV_KEY: ${DOTENV_KEY}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      APPLICATION_MODULE: ${APPLICATION_MODULE}
      API_VERSION: ${API_VERSION}
      API_BASE: ${API_BASE}
    networks:
      - laporan-network
    volumes:
      - type: bind
        source: /home/engineer/adameds/.env.vault
        target: /adameds-laporan/.env.vault
networks:
  laporan-network:
    driver: bridge